// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'NuxtLogo': typeof import("../components/NuxtLogo.vue")['default'],
    'Tutorial': typeof import("../components/Tutorial.vue")['default'],
    'Category': typeof import("../components/category/Index.vue")['default'],
    'Login': typeof import("../components/login/Index.vue")['default'],
    'NewsCount': typeof import("../components/news/Count.vue")['default'],
    'News': typeof import("../components/news/Index.vue")['default'],
    'NewsSearch': typeof import("../components/news/Search.vue")['default'],
    'UiAccordion': typeof import("../components/ui/Accordion.vue")['default'],
    'UiButton': typeof import("../components/ui/Button.vue")['default'],
    'UiCard': typeof import("../components/ui/Card.vue")['default'],
    'UiDataTable': typeof import("../components/ui/DataTable.vue")['default'],
    'UiDropDownList': typeof import("../components/ui/DropDownList.vue")['default'],
    'UiPassword': typeof import("../components/ui/Password.vue")['default'],
    'UiProfileIcon': typeof import("../components/ui/ProfileIcon.vue")['default'],
    'UiTextField': typeof import("../components/ui/TextField.vue")['default'],
    'UiTooltip': typeof import("../components/ui/Tooltip.vue")['default'],
    'UiTree': typeof import("../components/ui/Tree.vue")['default'],
    'Writing': typeof import("../components/writing/Index.vue")['default'],
    'ConsoleLogin': typeof import("../components/console/login/Index.vue")['default']
    'LazyNuxtLogo': typeof import("../components/NuxtLogo.vue")['default'],
    'LazyTutorial': typeof import("../components/Tutorial.vue")['default'],
    'LazyCategory': typeof import("../components/category/Index.vue")['default'],
    'LazyLogin': typeof import("../components/login/Index.vue")['default'],
    'LazyNewsCount': typeof import("../components/news/Count.vue")['default'],
    'LazyNews': typeof import("../components/news/Index.vue")['default'],
    'LazyNewsSearch': typeof import("../components/news/Search.vue")['default'],
    'LazyUiAccordion': typeof import("../components/ui/Accordion.vue")['default'],
    'LazyUiButton': typeof import("../components/ui/Button.vue")['default'],
    'LazyUiCard': typeof import("../components/ui/Card.vue")['default'],
    'LazyUiDataTable': typeof import("../components/ui/DataTable.vue")['default'],
    'LazyUiDropDownList': typeof import("../components/ui/DropDownList.vue")['default'],
    'LazyUiPassword': typeof import("../components/ui/Password.vue")['default'],
    'LazyUiProfileIcon': typeof import("../components/ui/ProfileIcon.vue")['default'],
    'LazyUiTextField': typeof import("../components/ui/TextField.vue")['default'],
    'LazyUiTooltip': typeof import("../components/ui/Tooltip.vue")['default'],
    'LazyUiTree': typeof import("../components/ui/Tree.vue")['default'],
    'LazyWriting': typeof import("../components/writing/Index.vue")['default'],
    'LazyConsoleLogin': typeof import("../components/console/login/Index.vue")['default']
  }
}
export const NuxtLogo: typeof import("../components/NuxtLogo.vue")['default']
export const Tutorial: typeof import("../components/Tutorial.vue")['default']
export const Category: typeof import("../components/category/Index.vue")['default']
export const Login: typeof import("../components/login/Index.vue")['default']
export const NewsCount: typeof import("../components/news/Count.vue")['default']
export const News: typeof import("../components/news/Index.vue")['default']
export const NewsSearch: typeof import("../components/news/Search.vue")['default']
export const UiAccordion: typeof import("../components/ui/Accordion.vue")['default']
export const UiButton: typeof import("../components/ui/Button.vue")['default']
export const UiCard: typeof import("../components/ui/Card.vue")['default']
export const UiDataTable: typeof import("../components/ui/DataTable.vue")['default']
export const UiDropDownList: typeof import("../components/ui/DropDownList.vue")['default']
export const UiPassword: typeof import("../components/ui/Password.vue")['default']
export const UiProfileIcon: typeof import("../components/ui/ProfileIcon.vue")['default']
export const UiTextField: typeof import("../components/ui/TextField.vue")['default']
export const UiTooltip: typeof import("../components/ui/Tooltip.vue")['default']
export const UiTree: typeof import("../components/ui/Tree.vue")['default']
export const Writing: typeof import("../components/writing/Index.vue")['default']
export const ConsoleLogin: typeof import("../components/console/login/Index.vue")['default']
export const LazyNuxtLogo: typeof import("../components/NuxtLogo.vue")['default']
export const LazyTutorial: typeof import("../components/Tutorial.vue")['default']
export const LazyCategory: typeof import("../components/category/Index.vue")['default']
export const LazyLogin: typeof import("../components/login/Index.vue")['default']
export const LazyNewsCount: typeof import("../components/news/Count.vue")['default']
export const LazyNews: typeof import("../components/news/Index.vue")['default']
export const LazyNewsSearch: typeof import("../components/news/Search.vue")['default']
export const LazyUiAccordion: typeof import("../components/ui/Accordion.vue")['default']
export const LazyUiButton: typeof import("../components/ui/Button.vue")['default']
export const LazyUiCard: typeof import("../components/ui/Card.vue")['default']
export const LazyUiDataTable: typeof import("../components/ui/DataTable.vue")['default']
export const LazyUiDropDownList: typeof import("../components/ui/DropDownList.vue")['default']
export const LazyUiPassword: typeof import("../components/ui/Password.vue")['default']
export const LazyUiProfileIcon: typeof import("../components/ui/ProfileIcon.vue")['default']
export const LazyUiTextField: typeof import("../components/ui/TextField.vue")['default']
export const LazyUiTooltip: typeof import("../components/ui/Tooltip.vue")['default']
export const LazyUiTree: typeof import("../components/ui/Tree.vue")['default']
export const LazyWriting: typeof import("../components/writing/Index.vue")['default']
export const LazyConsoleLogin: typeof import("../components/console/login/Index.vue")['default']
export const componentNames: string[]
