// Generated by nuxi
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path="types/components.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/nitro.d.ts" />
/// <reference path="types/auto-imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
